blog/urls.py
from django.conf.urls import url 
from django.urls import path, re_path
from django.views.i18n import JavaScriptCatalog
from .views import PostDetail, CategoryPost, Search, SubscriberCreate, activate
from blog.feeds import LatestPostsFeed
app_name = 'blog'
urlpatterns = [
    re_path(r'^(?:(?P<cat>[-\w]+)/)?(?:(?P<subcat>[-\w]+)/)?_(?P<slug>[-\w]+)/$', PostDetail.as_view(), name='post_detail'),
    re_path(r'^(?:(?P<cat>[-\w]+)/)?(?:(?P<subcat>[-\w]+)/)?$', CategoryPost.as_view(), name='post_by_category'),
    path('subscriber/create/', SubscriberCreate),
    path('activate/<str:uid64>/<str:token>/', activate, name='activate'),
    path('jsi18n', JavaScriptCatalog.as_view(), name='javascript-catalog'),
]

rad/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls import include, url
from django.urls import path
from rad.views import HomeView, BlogHomeView
from django.views.defaults import permission_denied, page_not_found, server_error
# from django_email_verification import urls as mail_urls
from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import PostSitemap
from blog.feeds import LatestPostsFeed
from blog.views import Search



sitemaps = {
    'posts': PostSitemap,
}   


urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', HomeView.as_view(), name='index'),
    path('', BlogHomeView.as_view(), name='blog-index'),
    path('tag/<str:tag>/', HomeView.as_view(), name='post_by_tag'),
    url(r'^blog/feed/$', LatestPostsFeed(), name='post_feed'),
    path('blog/search/', Search.as_view(), name='search'),
    path('blog/', include('blog.urls', namespace="blog")),
    path('comments/', include('django_comments_xtd.urls')),
    path('', include('pagedown.urls')),
    url(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    # path('email/', include(mail_urls)),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += [
        path('__debug__', include(debug_toolbar.urls)),
    ]

templates/tags/_carousel.html
{% load extras %}
<div id="carousel-photos{{ post.id }}" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    {% for x in post.photos.count|times %}
    {% if forloop.first %}
    <li data-target="#carousel-photos{{ post.id }}" data-slide-to="{{ forloop.counter0 }}" class="active"></li>
    {% else %}
    <li data-target="#carousel-photos{{ post.id }}" data-slide-to="{{ forloop.counter0 }}"></li>
    {% endif %}
    {% endfor %}
  </ol>
  <div class="carousel-inner">
    {% for photo in post.photos.all %}
    {% if forloop.first %}
    <div class="carousel-item active">
      <img src="{{ photo.file.url }}" class="d-block carousel-image mw-100" alt="...">
    </div>
    {% else %}
    <div class="carousel-item">
      <img src="{{ photo.file.url }}" class="d-block carousel-image mw-100" alt="...">
    </div>
    {% endif %}
    {% endfor %}
  </div>
  <a class="carousel-control-prev" href="#carousel-photos{{ post.id }}" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carousel-photos{{ post.id }}" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

templates/tags/_category_list.html
{% load static %}
{% for category in categories %}
{% if category.children.all %}
<li {% if category.slug in request.path and '/tag' not in request.path %}class="nav-item dropdown active"{% else %}class="nav-item dropdown"{% endif %}>
    <a class="nav-link d-inline-block" href="{% url 'blog:post_by_category' category.slug %}">{{ category.name }}</a>
    <a href="#" class="d-inline-block float-right text-decoration-none d-lg-none data-toggle" aria-haspopup="true" id="navbarDropdown" aria-expanded="false" data-toggle="dropdown" role="button" ><i class="fas fa-xs fa-plus align-middle right"></i></a>
    <div class="dropdown-menu p-0 m-0" aria-labelledby="navbarDropdown">
        {% for i in category.children.all %}
        <a {% if i.slug in request.path and '/tag' not in request.path %}class="dropdown-item active"{% else %}class="dropdown-item"{% endif %} href="{% url 'blog:post_by_category' category.slug i.slug %}">{{ i.name }}</a>
        {% if not forloop.last %}                
        <div class="dropdown-divider m-0"></div>
        {% endif %}
        {% endfor %}
    </div>
</li>
{% else %}
<li {% if category.slug in request.path %}class="nav-item active"{% else %}class="nav-item dropdown"{% endif %}>
    <a class="nav-link" href="{% url 'blog:post_by_category' category.slug %}">{{ category.name }}</a>
{% endif %}
{% endfor %}

templates/tags/_contact_us.html
{% load crispy_forms_tags %}
<div class="modal fade" id="contact-us" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h3 class="modal-title font-weight-lighter" id="exampleModalCenterTitle">We Love To Hear From You <i class="fas fa-user-ninja"></i></h3>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <form method="post" id="contact">
            {% csrf_token %}
            {{ form | crispy }}
        </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="submit" form="contact" class="btn btn-primary">Send</button>
      </div>
    </div>
  </div>
</div>

templates/tags/_side_bar.html
{% load extras %}
<div class="col-lg-4 col-md-5 d-none d-md-block mt-3 float-right ">
    <div class="card mb-5">
        <h5 class="card-header bg-warning"><i class="fas fa-plus"></i> Recent Posts</h5>
        <div class="card-body bg-danger">
            <ul class="list-group list-group-flush">
                {% for post in posts %}
                    <li class="list-group-item bg-dark"><a class="card-text text-decoration-none text-success" href="{{ post.get_absolute_url }}"> {{ post.title }}</a>
                    <small class="text-muted">{{ post.publish_date|timesince }}</small></li>     
                {% empty %}
                    Nothing 
                {% endfor %}
            </ul>
        </div>
    </div> 
    {% subscribe %}
</div>
<div class="col-sm-12  d-md-none d-sm-block mt-3 mb-3">
    <div class="card mb-5">
        <h5 class="card-header bg-info"><i class="fas fa-plus"></i> Recent Posts</h5>
        <div class="card-body">
            <ul class="list-group list-group-flush">
                {% for post in posts %}
                    <li class="list-group-item"><a class="card-text text-decoration-none text-success" href="{{ post.get_absolute_url }}"> {{ post.title }}</a>
                    <small class="text-muted">{{ post.publish_date|timesince }} ago</small></li>     
                {% empty %}
                    Nothing 
                {% endfor %}
            </ul>
        </div>
    </div>
    <div class="card mb-5">
        <h5 class="card-header text-center"><i class="fas fa-book-reader"></i> Stay in touch</h5>
        <div class="card-body">
            <p class="lead"> Sign up for our newsletter to get latest updates, news & good tips on our Blog.
                We hate spam as much as you do !
            </p>
            {% subscribe %}
        </div>
    </div>
</div>

templates/tags/_subscriber.html
{% load crispy_forms_tags %}
<form method="post" id="subscribe_form">
    {% csrf_token %}
    {{ form | crispy }}
    <button type="submit" class="btn btn-dark rounded-0 w-100 "><i class="fas fa-envelope"></i> Subscribe to get notified <strong>!</strong></button>
    <div id="result"></div>
</form>