blog/urls.py
from django.conf.urls import url 
from django.urls import path, re_path
from django.views.i18n import JavaScriptCatalog
from .views import PostDetail, CategoryPost, Search, SubscriberCreate, activate
from blog.feeds import LatestPostsFeed
app_name = 'blog'
urlpatterns = [
    re_path(r'^(?:(?P<cat>[-\w]+)/)?(?:(?P<subcat>[-\w]+)/)?_(?P<slug>[-\w]+)/$', PostDetail.as_view(), name='post_detail'),
    re_path(r'^(?:(?P<cat>[-\w]+)/)?(?:(?P<subcat>[-\w]+)/)?$', CategoryPost.as_view(), name='post_by_category'),
    path('subscriber/create/', SubscriberCreate),
    path('activate/<str:uid64>/<str:token>/', activate, name='activate'),
    path('jsi18n', JavaScriptCatalog.as_view(), name='javascript-catalog'),
]

rad/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls import include, url
from django.urls import path
from rad.views import HomeView, BlogHomeView
from django.views.defaults import permission_denied, page_not_found, server_error
# from django_email_verification import urls as mail_urls
from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import PostSitemap
from blog.feeds import LatestPostsFeed
from blog.views import Search



sitemaps = {
    'posts': PostSitemap,
}   


urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', HomeView.as_view(), name='index'),
    path('', BlogHomeView.as_view(), name='blog-index'),
    path('tag/<str:tag>/', HomeView.as_view(), name='post_by_tag'),
    url(r'^blog/feed/$', LatestPostsFeed(), name='post_feed'),
    path('blog/search/', Search.as_view(), name='search'),
    path('blog/', include('blog.urls', namespace="blog")),
    path('comments/', include('django_comments_xtd.urls')),
    path('', include('pagedown.urls')),
    url(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    # path('email/', include(mail_urls)),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += [
        path('__debug__', include(debug_toolbar.urls)),
    ]

blog/models.py
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.utils.safestring import mark_safe
from markdown_deux import markdown
from django.template.defaultfilters import slugify
from django.conf import settings
from mptt.models import MPTTModel, TreeForeignKey
from taggit.managers import TaggableManager
from blog.utils import get_read_time
# from django.db.models.signals import  
import uuid


User = settings.AUTH_USER_MODEL
# Create your models here.
def images_directory_path(instance, filename):
    return '/'.join(['upload', str(instance.post.timestamp.date()), 
                        str(instance.post.id ) + " " + str(instance.post.title), 
                        str(uuid.uuid4().hex + ".png")])

class PostQuerySet(models.QuerySet):
    def published(self):
        now = timezone.now()
        return self.filter(draft=False, publish_date__lte=now)


class PostManager(models.Manager):
    def get_queryset(self):
        return PostQuerySet(self.model, using=self._db)

    def published(self):
        return self.get_queryset().published()

    def search(self, query=None):
        if query is None:
            return self.get_queryset().none()
        return self.get_queryset().published().search(query)

class Category(MPTTModel):
    name = models.CharField(max_length=25, db_index=True)
    slug = models.SlugField(max_length=50, db_index=True, editable=False, allow_unicode=True)
    parent = TreeForeignKey('self', null=True, blank=True, on_delete=models.CASCADE, related_name='children', db_index=True)
    position = models.PositiveSmallIntegerField(unique=True, db_index=True)
    class MPTTMeta:
        order_insertion_by = ['position']

    class Meta:
        unique_together = ('slug', 'parent',)
        verbose_name_plural = ("Categories")
        ordering = ('name',)
        verbose_name = 'Category'

    def get_absolute_url(self):
        return reverse('blog:post_by_category',args=[self.slug])

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super().save(*args, **kwargs)

    def get_slug_list(self):
        try:
            ancestors = self.get_ancestors(include_self=True)
        except:
            ancestors = []
        else:
            ancestors = [ i.slug for i in ancestors ]
        slugs = []
        for i in range(len(ancestors)):
            slugs.append('/'.join(ancestors[:i+1]))
        return slugs
        
    def __str__(self):
        return self.name


class Post(models.Model):
    author = models.ForeignKey(User, default=1, on_delete=models.CASCADE, related_name='authorpost')
    category = TreeForeignKey(Category, related_name='postcategory', on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    body = models.TextField()
    read_time = models.PositiveSmallIntegerField(null=True, blank=True, editable=False,)
    draft = models.BooleanField(default=False)
    slug = models.SlugField(max_length=200, db_index=True, unique=True, editable=False, allow_unicode=True)
    publish_date = models.DateTimeField(auto_now=False, auto_now_add=False, null=True, blank=True)
    timestamp = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    objects = PostManager()
    tags = TaggableManager()

    class Meta:
        ordering = ['-publish_date', '-updated', '-timestamp']
        index_together = (('id', 'slug'),)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        self.read_time = get_read_time(self.body)
        super().save(*args, **kwargs)
    def get_markdown(self):
        return mark_safe(markdown(self.body))

    def get_absolute_url(self):
        return reverse('blog:post_detail', kwargs={"slug":self.slug,})

    def get_slug_list(self):
        k = self.category
        breadcrumb = []
        while k is not None:
            breadcrumb.append(k)
            k = k.parent
        return breadcrumb
        # for i in range(len(breadcrumb) - 1):
        #     breadcrumb[i] = '/'.join(breadcrumb[-1:i-1:-1])
        # return breadcrumb[-1:0:-1]

    def __str__(self):
        return "{} publsihed on {}".format(self.title, self.timestamp)


class Photo(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='photos')
    file = models.ImageField(upload_to=images_directory_path, unique=True, null=True, blank=True)
    timestamp = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.post.title

class Subscriber(models.Model):
    email = models.EmailField()
    timestamp = models.DateTimeField(auto_now_add=True, db_index=True)
    active = models.BooleanField(default=False, db_index=True)

    class Meta:
        # unique_together = ('slug', 'parent',)
        verbose_name_plural = ("Subscribers")
        ordering = ('timestamp',)
        verbose_name = 'Subscriber'

    def __str__(self):
        return self.email
    

blog/forms.py
from django import forms
from pagedown.widgets import AdminPagedownWidget
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout
from blog.models import Subscriber, Post

class SubscribeForm(forms.Form):
    subscribe_email = forms.EmailField( widget=forms.TextInput(attrs={
        "type":"email",
        "name":"email",
        "id":"email",
        "placeholder": "Type your email address...",
        "class": "rounded-0",
    }), label="")
    class Meta:
        model = Subscriber
class PostBodyForm(forms.ModelForm):
    body = forms.CharField(widget=AdminPagedownWidget)

    class Meta:
        model = Post
        fields = "__all__"

blog/views.py
from django.shortcuts import render, redirect
from django.contrib.sites.shortcuts import get_current_site
from django.contrib import messages
from django.urls import reverse
from django.shortcuts import get_object_or_404
from django.views import View
from blog.models import Category, Photo, Post, Subscriber
from rad.forms import EmailPostForm
from django.urls import reverse_lazy
from django.http import Http404
from django.views import generic
from django.contrib.sites.shortcuts import get_current_site
# from django.template.loader import render_to_string
from django.views.generic.base import TemplateView, TemplateResponseMixin, ContextMixin
from django.views.generic.edit import FormView, FormMixin
from django.http import HttpResponseRedirect, JsonResponse, HttpResponse
from haystack.query import SearchQuerySet
from haystack.generic_views import SearchView
import json
import logging
logger = logging.getLogger(__name__)
# Create your views here.
from blog.tasks import contact_us, subscriber_verification
from django.utils.encoding import force_text
from django.utils.http import urlsafe_base64_decode
from django.db.models import Count
from blog.utils import get_read_time

def mailto(request):
    form = EmailPostForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        contact_us.delay(cd['name'], cd['email'], cd['comments'])
        messages.success(request, "<strong>Hi {} !</strong> Your mail has been sent successfully, thank you.".format(cd['name']))
    else:
        messages.error(request, "<strong>Hi {} !</strong> Unfortunately your mail wasn't sent, try again.".format(cd['name']))


class CategoryPost(generic.ListView):
    model = Post
    paginate_by = 1
    template_name = 'blog/post_by_category.html'
    def get_queryset(self):
        qs = super().get_queryset()   
        category_slug = self.kwargs["cat"]
        parent = Category.objects.get(parent=None, slug=category_slug)
        try:
            sub_category_slug = self.kwargs["subcat"]
        except KeyError:
            sub_category_slug = None
        if sub_category_slug:
            sub_category = Category.objects.get(parent=parent, slug=sub_category_slug)
            return qs.filter(category=sub_category).published()
        else:
            return qs.filter(category__in=parent.get_descendants(include_self=True))

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(**kwargs)
        return context
    
    def post(self, request, *args, **kwargs):
        mailto(request)
        return HttpResponseRedirect(request.path_info)


class PostDetail(generic.DetailView):
    model = Post
    template_name_suffix = '_detail'
    def get_queryset(self):
        qs = super().get_queryset()    
        post_slug = self.kwargs["slug"]
        logger.info(post_slug)
        return qs.filter(slug=post_slug)   

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(**kwargs)
        post_tags_ids = self.object.tags.values_list('id', flat=True)
        similar_posts = Post.objects.filter(tags__in=post_tags_ids).exclude(id=self.object.id).published()
        similar_posts = similar_posts.annotate(same_tags=Count('tags')).order_by('-same_tags','-publish_date')[:4]
        context["similiar_post"] = similar_posts
        return context

    def post(self, request, *args, **kwargs):
        mailto(request)
        return HttpResponseRedirect(request.path_info)
    

class Search(SearchView):
    template_name = 'blog/post_search.html'

    def get(self, request, **kwargs):
        import ast 
        query = request.GET.get('query', '')
        results = SearchQuerySet().models(Post).filter(content=query).load_all()
        search_results = [resultsx for resultsx in results]
        for x in range(len(search_results)):
            search_results[x].title = ast.literal_eval(search_results[x].title)[0]
            search_results[x].url = ast.literal_eval(search_results[x].url)[0]
        total = results.count()
        return render(request, self.template_name, {'results':search_results, 'total':total, 'query':query})
    def post(self, request, *args, **kwargs):
        mailto(request)
        return HttpResponseRedirect(request.path_info)

def SubscriberCreate(request):
    if request.method == 'POST':
        email = request.POST['email']
        data = {}
        data = {
            'is_taken': Subscriber.objects.filter(email=email, active=True).exists(),
            'not_verified': Subscriber.objects.filter(email=email, active=False).exists()
        }
        if data['is_taken'] or data['not_verified']:
            return JsonResponse(data)
        else:
            subscriber = Subscriber.objects.create(email=email)
            current_site = "http://192.168.43.195:8000"
            subscriber_verification.delay(subscriber.id, current_site, email)
    return JsonResponse(data)

from blog.tokens import default_token_generator
def activate(request, uid64, token):
    try:
        uid = force_text(urlsafe_base64_decode(uid64))
        subscriber = Subscriber.objects.get(pk=uid)
    except (TypeError, ValueError, OverflowError, Subscriber.DoesNotExist):
        subscriber = None
    if subscriber and default_token_generator.check_token(subscriber, token):
        subscriber.active = True
        subscriber.save()
        return HttpResponse('Thank you for your email confirmation.')
    else:
        return HttpResponse('Activation link invalid')

blog/templates/blog/post_by_category.html
{% extends 'blog_base.html' %}
{% load comments %}
{% load markdown_deux_tags %}
{% load extras %}
{% block content %}
  <div class="container">
    {% if title %}
    <p class="display-4">{{ title }}</p>
    {% endif %}
    <div class="row">
      <div class="col-lg-8 col-md-7 mt-3 left">
        {% for post in post_list %}
        <div class="card mb-4">
          <div class="card-body">
            <h2 class="card-title mb-0">{{ post.title }}</h2>
            <small><em><i class="far fa-clock"></i>{% if post.read_time <= 1 %} 1 minute{% else %}{{ post.read_time }} minutes{% endif %} read</em></small>
            {% if post.photos %}
            <div class='d-flex justify-content-center align-items-center carousel-wrapper w-100 bg-dark'>
              {% if post.photos.count == 1%}
              <img src="{{ post.photos.first.file.url }}" class="img-fluid mw-100 carousel-image">
              {% else %}
              {% carousel post.id %}
              {% endif %}
            </div>
            {% endif %}
            <small class="card-text text-muted"> <i class="fas fa-calendar-alt"></i> {{ post.publish_date}}
              {% get_comment_count for post as comment_count %}
              {% if comment_count %}
              &sdot;&nbsp; <i class="fas fa-comment-dots"></i> {{ comment_count }} comment{{ comment_count|pluralize }}
              {% else %}
              &sdot;&nbsp; <i class="fas fa-comment-dots"></i> 0 comment
              {% endif %}
              <p class="tags">
              {% if post.tag.all.count == 1 %}
              <i class="fas fa-tag"> </i> Tag:
              {% else %}
              <i class="fas fa-tags"> </i> Tags:
              {% endif %}
                {% for tag in post.tags.all %}
                <a href="{% url 'post_by_tag' tag.slug %}" style="text-decoration:none;">
                  <span class="badge badge-secondary">{{ tag.name }}</span>
                </a>
                {% endfor %}
              </p>
            </small>
            <p class="card-text post-body">{{post.get_markdown|truncatewords:50}}</p>
            <a {% if post.category.slug not in request.path %}href="{% url 'blog:post_detail' cat=post.category.parent.slug slug=post.slug%}"{% else %}href="{% url 'blog:post_detail' cat=post.category.parent.slug subcat=post.category.slug slug=post.slug %}"{% endif %}class="btn btn-primary">Read More &rarr;</a>
          </div>
        </div>
        {% empty %}
          <p>Post never dey g...
        {% endfor %}
      </div>
      <div class="col-sm-12 d-md-none d-sm-block">
        {% include 'assests/pagination.html' %}
      </div>
      {% side_bar %}
    </div>
  </div>
  <div class="d-none d-md-block">
    {% include 'assests/pagination.html' %}
  </div>
{% endblock  %}

blog/templates/blog/post_detail.html
{% extends 'blog_base.html' %} 
{% load i18n %}
{% load crispy_forms_tags %}
{% load markdown_deux_tags %}
{% load static %}
{% load extras %}
{% load comments %}
{% load comments_xtd %}


{% block content %}


<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-8 card mb-4 col-lg-8">
      <div class="card-body">
        <p class="card-title mb-0" style="font-size:2.5em">{{ post.title }}</p>
        <small><em><i class="far fa-clock"></i>{% if post.read_time <= 1 %} 1 minute{% else %} {{ post.read_time }} minutes{% endif %} read</em></small>
        {% if post.photos %}
        <div class='d-flex justify-content-center align-items-center carousel-wrapper w-100 bg-dark'>
          {% if post.photos.count == 1%}
          <img src="{{ post.photos.first.file.url }}" class="img-fluid mw-100 carousel-image">
          {% else %}
          {% carousel post.id %}
          {% endif %}
        </div>
        {% endif %}
        <small class="card-text text-muted"> <i class="fas fa-calendar-alt"></i> {{ post.publish_date}}
          <p class="tags">
            {% if post.tag.all.count == 1 %}
            <i class="fas fa-tag"> </i> Tag:
            {% else %}
            <i class="fas fa-tags"> </i> Tags:
            {% endif %}
            {% for tag in post.tags.all %}
            <a href="{% url 'post_by_tag' tag.slug %}" style="text-decoration:none;">
              <span class="badge badge-secondary">{{ tag.name }}</span>
            </a>
            {% endfor %}
          </p>
        </small>
        <div class="post-body">
          {{ post.get_markdown }}
        </div>
      </div>
      <div id="comments"></div>
    </div>
    <div class="d-none d-lg-block col-lg-4 justify-content-center">
      <div class="card col-12 mb-3 " style="">
        <div class="row">
          <div class="col-12 px-0">
            <h5 class="card-header bg-info lead text-center"> <i class="fas fa-book-reader"></i> You might also like th{{ similiar_post|pluralize:"is,ese" }}</h5>
          </div>
        </div>
        {% for post in similiar_post %}
        <div class={% if not forloop.last %}"row no-gutters border-bottom border-secondary"{% else %}"row no-gutters"{% endif %}>
          <div class="col-3 p-1">
            <img src="{{ post.photos.first.file.url }}" class="card-img img-thumbnail rounded-circle" alt="..." style="width:50px;height:50px;">
          </div>
          <div class="col-9">
            <div class="card-body p-1">
              <a href="{{ post.get_absolute_url }}" class="text-de coration-none"><p class="text-secondary mb-0">{{ post.title }}</p></a>
              <p class="card-text"><small class="text-muted">{{ post.publish_date|timesince }}</small></p>
            </div>
          </div>
        </div>
        {% endfor %}
      </div>
    </div>
  </div>
  
  <div class="row d-lg-none justify-content-center">
    <div class="card col-md-8 col-12 mb-3 " style="">
      <div class="row">
        <div class="col-md-12 px-0">
          <h5 class="card-header lead bg-success text-center"> <i class="fas fa-book-reader"></i> You might also like th{{ similiar_post|pluralize:"is,ese" }}</h5>
        </div>
      </div>
      {% for post in similiar_post %}
      <div class="row no-gutters" {% if not forloop.last %}style="border-bottom:1px solid black;"{% endif %}>
        <div class="col-md-3 col-4 py-2 justify-content-center align-items-center d-flex">
          <img src="{{ post.photos.first.file.url }}" class="card-img img-thumbnail rounded-circle" alt="..." style="width:50px;height:50px;">
        </div>
        <div class="col-md-5 col-8">
          <div class="card-body pl-0 py-2">
            <a href="{{ post.get_absolute_url }}"><h5 class="card-title text-secondary mb-0">{{ post.title }}</h5></a>
            <p class="card-text"><small class="text-muted">{{ post.publish_date|timesince }}</small></p>
          </div>
        </div>
      </div>
      {% endfor %}    
    </div>
    <div class="card col-md-8 col-12 mb-3 mb-5">
      <h5 class="card-header text-center"><i class="fas fa-book-reader"></i> Stay in touch</h5>
      <div class="card-body">
        <p class="lead"> Sign up for our newsletter to get latest updates, news & good tips on our Blog.
          We hate spam as much as you do !
        </p>
        {% subscribe %}
      </div>
    </div>

  </div>

</div>

{% endblock content %}

{% block javascript %}
<script src="{% static 'js/react.production.min.js' %}"></script>
<script src="{% static 'js/react-dom.production.min.js' %}"></script>
<script>
  window.comments_props = {% get_commentbox_props for post %};
  {% comment %} window.comments_props_override = {
    poll_interval: 5000 // In milliseconds.
  }; {% endcomment %}
</script>
<script type="text/javascript" src="{% url 'blog:javascript-catalog' %}"></script>
<script src="{% static 'django_comments_xtd/js/vendor~plugin-2.6.1.js' %}"></script>
<script src="{% static 'django_comments_xtd/js/plugin-2.6.1.js' %}"></script>
<script>
$(function() {
  $('[data-toggle="tooltip"]').tooltip({html: true});
});
</script>

{% endblock %}

blog/templates/blog/post_search.html
{% extends 'blog_base.html' %} 
{% load static %}
{% load extras %}

{% block content %}


<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-8 card mb-4 col-lg-8">
        <h1 class="display-4">{{ total }} Result{{ total|pluralize }} found for "{{ query }}"</h1>
        <hr>
        <ul class="list-unstyled">
            {% for result in results %}
            <a href="{{ result.url }}"><li class="media">
                <img src="{{ result.object.photos.first.file.url }}" class="mr-3 image-fluid" style="height:50px;width:50px;" alt="...">
                <div class="media-body">
                <h5 class="mt-0 mb-1">{{ result.title }}</h5>
                {{ result.object.get_markdown|truncatewords:15 }}
                </div>
            </li></a>
            {% empty %}
            No post
            {% endfor%}
        </ul>
    </div>
  </div>
</div>
{% endblock content %}