blog/urls.py
from django.conf.urls import url 
from django.urls import path, re_path
from django.views.i18n import JavaScriptCatalog
from .views import PostDetail, CategoryPost, Search, SubscriberCreate, activate
from blog.feeds import LatestPostsFeed
app_name = 'blog'
urlpatterns = [
    re_path(r'^(?:(?P<cat>[-\w]+)/)?(?:(?P<subcat>[-\w]+)/)?_(?P<slug>[-\w]+)/$', PostDetail.as_view(), name='post_detail'),
    re_path(r'^(?:(?P<cat>[-\w]+)/)?(?:(?P<subcat>[-\w]+)/)?$', CategoryPost.as_view(), name='post_by_category'),
    path('subscriber/create/', SubscriberCreate),
    path('activate/<str:uid64>/<str:token>/', activate, name='activate'),
    path('jsi18n', JavaScriptCatalog.as_view(), name='javascript-catalog'),
]

rad/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls import include, url
from django.urls import path
from rad.views import HomeView, BlogHomeView
from django.views.defaults import permission_denied, page_not_found, server_error
# from django_email_verification import urls as mail_urls
from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import PostSitemap
from blog.feeds import LatestPostsFeed
from blog.views import Search



sitemaps = {
    'posts': PostSitemap,
}   


urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', HomeView.as_view(), name='index'),
    path('', BlogHomeView.as_view(), name='blog-index'),
    path('tag/<str:tag>/', HomeView.as_view(), name='post_by_tag'),
    url(r'^blog/feed/$', LatestPostsFeed(), name='post_feed'),
    path('blog/search/', Search.as_view(), name='search'),
    path('blog/', include('blog.urls', namespace="blog")),
    path('comments/', include('django_comments_xtd.urls')),
    path('', include('pagedown.urls')),
    url(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    # path('email/', include(mail_urls)),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += [
        path('__debug__', include(debug_toolbar.urls)),
    ]

templates/subscription/confirm_template.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>rad | Confirmation</title>
        <style>
            body{color: blue;}
        </style>
    </head>
    <body>
        {% if success %}
            You have confirmed your mail!
        {% else %}
            Error, invalid token!
        {% endif %} 
    </body>
</html>

templates/subscription/post_notification.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">  
    </head>
    <body>
        {% for post in posts %}
        <div class="media">
            <img src={{ post.photos.first.file.url }} class="align-self-center image-thumbnail mr-3" alt="...">
            <div class="media-body">
                <h5 class="mt-0">{{ post.title }}</h5>
                <p>{{ post.body | truncatewords:30 }}</p>
                <a href="{{domain}}{{ post.get_absolute_url }}" class="mb-0">Read More >></a>
            </div>
        </div>
        {% endfor %}
    </body>
</html>

templates/subscription/subscriber.html
{% autoescape off %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <style>
            h1{color: blue;}
        </style>
    </head>
    <body>
        <h1>You are almost there!</h1><br>
        <h2>Please click <a href="{{ domain }}{% url 'blog:activate' uid token %}">here</a> to confirm your registration. 
        {{ i }}
    </body>
</html>
{% endautoescape %}